import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <nav className={ "bg-sky-400 text-lg mb-4 " }>
          <ul className={"flex justify-center gap-7 p-4 "}>
            <Link href="/"><li>Home</li></Link>
            <Link href="posts"><li>Posts</li></Link>
            <Link href="articles"><li>Articles</li></Link>
          </ul>
        </nav>
        { children }
      </body>
    </html>
  );
}
